#
# lit-explore: PubTator Central config
#

# where to store raw & processed data
output_dir: "/data/pubtator"

filtering:
  # maximum number of entries allow for a single article; in some cases, a single article may be
  # assoicated with >100k annotations in PubTator, indicating a likely issue with the upstream data
  # generation pipeline;
  # 151 / 26923216 articles are associated with >= 1000 annotations at the time of writing (Dec 2022)
  pmid_max_entries: 1000

  # minimum number of occurrences requires for a given mention to be kept
  mentions_min_freq: 2

  # minimum number of occurrences requires for a given concept id to be kept (after filtering by
  # mentions field)
  concept_id_min_freq: 2
